import anki from '@app/locales/zh-CN/anki.json';
import chatV2 from '@app/locales/zh-CN/chatV2.json';
import common from '@app/locales/zh-CN/common.json';
import dragDrop from '@app/locales/zh-CN/drag_drop.json';
import essayGrading from '@app/locales/zh-CN/essay_grading.json';
import examSheet from '@app/locales/zh-CN/exam_sheet.json';
import flashcards from '@app/locales/zh-CN/flashcards.json';
import generativeUi from '@app/locales/zh-CN/generativeUi.json';
import learningHub from '@app/locales/zh-CN/learningHub.json';
import mindmap from '@app/locales/zh-CN/mindmap.json';
import practice from '@app/locales/zh-CN/practice.json';
import settings from '@app/locales/zh-CN/settings.json';
import sidebar from '@app/locales/zh-CN/sidebar.json';
import stats from '@app/locales/zh-CN/stats.json';
import todo from '@app/locales/zh-CN/todo.json';
import translation from '@app/locales/zh-CN/translation.json';
import workbench from '@app/locales/zh-CN/workbench.json';

const NS = {
  anki,
  chatV2,
  common,
  drag_drop: dragDrop,
  essay_grading: essayGrading,
  exam_sheet: examSheet,
  flashcards,
  generativeUi,
  learningHub,
  mindmap,
  practice,
  settings,
  sidebar,
  stats,
  todo,
  translation,
  workbench,
} as const;
type Ns = keyof typeof NS;

/**
 * 界面文案一律从主应用 zh-CN locale 读取；key 失效时直接抛错，
 * 让文案漂移在渲染阶段暴露，而不是静默出现过时字符串。
 */
export const tr = (ns: Ns, key: string, vars: Record<string, string | number> = {}): string => {
  let node: unknown = NS[ns];
  for (const part of key.split('.')) {
    node = node && typeof node === 'object' ? (node as Record<string, unknown>)[part] : undefined;
  }
  if (typeof node !== 'string') throw new Error(`[strings] missing zh-CN key ${ns}:${key}`);
  return node.replace(/\{\{(\w+)\}\}/g, (_, v: string) => String(vars[v] ?? `{{${v}}}`));
};

export const S = {
  emptyTitle: tr('chatV2', 'messageList.empty.primaryAction'),
  placeholder: tr('chatV2', 'inputBar.placeholder'),
  refAdded: tr('chatV2', 'selectionRef.added'),
  sel: {
    copy: tr('chatV2', 'selectionToolbar.copy'),
    explain: tr('chatV2', 'selectionToolbar.explain'),
    translate: tr('chatV2', 'selectionToolbar.translate'),
    saveAsNote: tr('chatV2', 'selectionToolbar.saveAsNote'),
    makeCards: tr('chatV2', 'selectionToolbar.makeCards'),
    addToChat: tr('chatV2', 'selectionToolbar.addToChat'),
    addAsContext: tr('chatV2', 'selectionToolbar.addAsContext'),
  },
  thinking: (s: number) => tr('chatV2', 'timeline.thinking.inProgress', { seconds: s }),
  thought: (s: number) => tr('chatV2', 'timeline.thinking.completed', { seconds: s }),
  searching: tr('chatV2', 'timeline.retrieval.searching'),
  retrievalSummary: (n: number) => tr('chatV2', 'timeline.retrieval.summary', { count: n }),
  unifiedSearch: tr('common', 'mcp.tools.unified_search'),
  memorySearch: tr('common', 'mcp.tools.memory_search'),
  nodeCount: (n: number) => tr('mindmap', 'embed.nodeCount', { count: n }),
  open: tr('common', 'actions.open'),
  mm: {
    outline: tr('mindmap', 'toolbar.outline'),
    mindmap: tr('mindmap', 'toolbar.mindmap'),
    switchStructure: tr('mindmap', 'toolbar.switchStructure'),
    styleSettings: tr('mindmap', 'toolbar.styleSettings'),
    hideCompleted: tr('mindmap', 'toolbar.hideCompleted'),
    saved: tr('mindmap', 'toolbar.saved'),
    learning: tr('mindmap', 'toolbar.learning'),
    recite: tr('mindmap', 'recite.title'),
    reviewStart: tr('mindmap', 'recite.reviewStart'),
    revealAll: tr('mindmap', 'recite.revealAll'),
    resetAll: tr('mindmap', 'recite.resetAll'),
    exit: tr('mindmap', 'recite.exit'),
    remaining: (n: number) => tr('mindmap', 'recite.remaining', { count: n }),
    structMindmap: tr('chatV2', 'mindmapCitation.mindmap'),
    structLogic: tr('mindmap', 'structure.logic'),
    structOrg: tr('mindmap', 'structure.orgchart'),
    timeline: tr('mindmap', 'layouts.timeline'),
    presetBalanced: tr('mindmap', 'presets.mindmapBalanced'),
    presetLogic: tr('mindmap', 'presets.logicTreeRight'),
    presetOrg: tr('mindmap', 'presets.orgchartDown'),
    presetTimeline: tr('mindmap', 'presets.timelineRight'),
    structureCurrent: tr('mindmap', 'structure.current'),
  },
  anki: {
    generating: tr('chatV2', 'blocks.ankiCards.loading'),
    title: tr('chatV2', 'blocks.ankiCards.title'),
    add: tr('chatV2', 'blocks.ankiCards.addToLibrary'),
    added: tr('chatV2', 'blocks.ankiCards.addedToLibrary'),
    review: tr('chatV2', 'blocks.ankiCards.reviewBatch'),
    edit: tr('anki', 'chatV2.editInline'),
    total: (n: number) => tr('anki', 'chatV2.totalCards', { count: n }),
    clickToEdit: tr('anki', 'chatV2.clickToEdit'),
    saved: tr('anki', 'chatV2.saved'),
  },
  fc: {
    showAnswer: tr('flashcards', 'review.showAnswer'),
    again: tr('flashcards', 'session.again'),
    hard: tr('flashcards', 'session.hard'),
    good: tr('flashcards', 'session.good'),
    easy: tr('flashcards', 'session.easy'),
    front: tr('flashcards', 'session.front'),
    back: tr('flashcards', 'session.back'),
    tapToFlip: tr('flashcards', 'session.tapToFlip'),
    done: tr('flashcards', 'session.done'),
    doneHint: tr('flashcards', 'review.doneHint'),
    statRated: tr('flashcards', 'review.statRated'),
    statTime: tr('flashcards', 'review.statTime'),
    statBestStreak: tr('flashcards', 'review.statBestStreak'),
    heatmap: tr('flashcards', 'stats.heatmap.title'),
    less: tr('flashcards', 'stats.heatmap.legendLess'),
    more: tr('flashcards', 'stats.heatmap.legendMore'),
    exit: tr('flashcards', 'session.exit'),
    undo: tr('flashcards', 'session.undo'),
    streak: (n: number) => tr('flashcards', 'review.streak', { count: n }),
    learningStep: tr('flashcards', 'review.learningStep'),
    newCount: (n: number) => tr('flashcards', 'review.newCount', { count: n }),
    learnCount: (n: number) => tr('flashcards', 'review.learnCount', { count: n }),
    ratedRemaining: (rated: number, left: number) => tr('flashcards', 'review.ratedRemaining', { rated, left }),
    undoNudge: (rating: string) => tr('flashcards', 'review.undoNudgeRated', { rating }),
  },
  fcTabs: {
    today: tr('flashcards', 'tabs.today'),
    library: tr('flashcards', 'tabs.library'),
    statistics: tr('flashcards', 'tabs.statistics'),
    settings: tr('flashcards', 'tabs.settings'),
  },
  fcStats: {
    title: tr('flashcards', 'statistics.title'),
    subtitle: tr('flashcards', 'statistics.subtitle'),
    refresh: tr('flashcards', 'statistics.refresh'),
    overview: tr('flashcards', 'statistics.overview'),
    streak: (n: number) => `${tr('flashcards', 'stats.streak.current')} ${tr('flashcards', 'stats.streak.days', { count: n })}`,
    reviewsToday: tr('flashcards', 'statistics.reviewsToday'),
    due: tr('flashcards', 'statistics.due'),
    learning: tr('flashcards', 'statistics.learning'),
    total: tr('flashcards', 'statistics.total'),
    heatSub: tr('flashcards', 'stats.heatmap.subtitle'),
    activeDays: (n: number) => tr('flashcards', 'stats.streak.activeDays', { count: n }),
    daily: tr('flashcards', 'stats.daily.title'),
    dailySub: tr('flashcards', 'stats.daily.subtitle', { days: 14 }),
    ratings: tr('flashcards', 'stats.ratings.title'),
  },
  radar: {
    title: tr('stats', 'knowledgeRadar.title'),
    mastery: tr('stats', 'knowledgeRadar.mastery'),
  },
  wb: {
    agenda: tr('workbench', 'agenda.label'),
    briefing: tr('generativeUi', 'workbench.briefing_label'),
    appsSearch: tr('workbench', 'appsPanel.searchPlaceholder'),
    allApps: tr('workbench', 'appsPanel.title'),
    sectionResources: tr('workbench', 'appsPanel.sectionResources'),
    sectionChat: tr('workbench', 'appsPanel.sectionChat'),
    operating: (label: string) => tr('workbench', 'agent.core.operating', { label }),
    filePreview: tr('workbench', 'apps.filePreview'),
    pomodoro: tr('workbench', 'apps.pomodoro'),
    files: tr('workbench', 'agentControlCenter.apps.files.name'),
    flashcards: tr('workbench', 'agentControlCenter.apps.flashcards.name'),
  },
  nav: {
    newChat: tr('sidebar', 'navigation.chat_v2'),
    learningHub: tr('sidebar', 'navigation.learning_hub'),
    todo: tr('common', 'navigation.todo'),
    skills: tr('sidebar', 'navigation.skills_management'),
    anki: tr('sidebar', 'navigation.anki_generation'),
    flashcards: tr('sidebar', 'navigation.flashcards'),
    templates: tr('anki', 'template_management.page_title'),
    settings: tr('sidebar', 'navigation.settings'),
    pinned: tr('sidebar', 'sections.pinned'),
    topics: tr('sidebar', 'sections.topics'),
    conversations: tr('sidebar', 'sections.conversations'),
    search: tr('sidebar', 'search.placeholder'),
    workbenchMode: tr('sidebar', 'navigation.workbench_mode'),
  },
  apps: {
    chat: tr('workbench', 'apps.chat.name'),
    note: tr('workbench', 'apps.note'),
    exam: tr('workbench', 'apps.exam'),
    translation: tr('workbench', 'apps.translation'),
    essay: tr('workbench', 'apps.essay'),
    filePreview: tr('workbench', 'apps.filePreview'),
    files: tr('workbench', 'apps.files'),
    todo: tr('workbench', 'apps.todo'),
    flashcards: tr('workbench', 'apps.flashcards'),
    settings: tr('workbench', 'apps.settings'),
    pomodoro: tr('workbench', 'apps.pomodoro'),
    textbook: tr('workbench', 'apps.textbook'),
    aiDashboard: tr('workbench', 'apps.aiDashboard'),
    sectionApps: tr('workbench', 'appsPanel.sectionApps'),
    sectionCommands: tr('workbench', 'appsPanel.sectionCommands'),
  },
  /** 学习桌面外壳：菜单栏 / Dock / 桌面快捷方式 / 小组件 */
  desk: {
    appName: tr('workbench', 'menubar.appName'),
    windowMenu: tr('workbench', 'menubar.windowMenu'),
    dockApps: tr('workbench', 'dock.apps'),
    agentDock: tr('workbench', 'agentControlCenter.title'),
    shortcut: {
      note: tr('learningHub', 'resourceType.note'),
      exam: tr('learningHub', 'resourceType.exam'),
      essay: tr('learningHub', 'resourceType.essay'),
      translation: tr('learningHub', 'resourceType.translation'),
      mindmap: tr('learningHub', 'resourceType.mindmap'),
    },
    agendaPending: (n: number) => tr('workbench', 'agenda.pendingCount', { count: n }),
    agendaOpen: tr('workbench', 'agenda.openTodo'),
    agendaMore: (n: number) => tr('workbench', 'agenda.more', { count: n }),
    agendaClear: tr('workbench', 'agenda.clear'),
    briefing: tr('generativeUi', 'workbench.briefing_label'),
    dueTitle: tr('generativeUi', 'workbench.briefing.due_flashcards_title'),
    dueTrend: tr('generativeUi', 'workbench.briefing.due_trend_due'),
    progressTitle: tr('generativeUi', 'workbench.briefing.progress_title'),
    startReview: tr('generativeUi', 'workbench.briefing.start_review'),
    openQbank: tr('generativeUi', 'workbench.briefing.open_qbank'),
  },
  todo: {
    searchLists: tr('todo', 'actions.searchLists'),
    search: tr('todo', 'actions.search'),
    smartViews: tr('todo', 'sections.smartViews'),
    lists: tr('todo', 'sections.lists'),
    views: {
      inbox: tr('todo', 'views.inbox'),
      today: tr('todo', 'views.today'),
      upcoming: tr('todo', 'views.upcoming'),
      matrix: tr('todo', 'views.matrix'),
      overdue: tr('todo', 'views.overdue'),
      completed: tr('todo', 'views.completed'),
    },
    automation: tr('todo', 'automation.title'),
    trash: tr('todo', 'trash.title'),
    quickAdd: tr('todo', 'actions.quickAddPlaceholder'),
    pending: tr('todo', 'stats.pending'),
    pomodoroLoad: (n: number) => tr('todo', 'stats.pomodoroLoad', { count: n }),
    progress: (done: number, total: number) => tr('todo', 'stats.progressTitle', { done, total }),
    priorityFilter: tr('todo', 'filters.priority'),
    sortManual: tr('todo', 'sort.manual'),
    showCompleted: tr('todo', 'filters.showCompleted'),
    select: tr('todo', 'bulk.selectMode'),
    reviewTitle: (n: number) => tr('todo', 'reviewLink.title', { count: n }),
    reviewCards: (n: number) => tr('todo', 'reviewLink.cards', { count: n }),
    reviewAction: tr('todo', 'reviewLink.action'),
    today: tr('todo', 'dates.today'),
    priority: { high: tr('todo', 'priority.high'), medium: tr('todo', 'priority.medium'), low: tr('todo', 'priority.low') },
    startFocus: tr('todo', 'actions.startFocusSession'),
    pomoIdle: tr('todo', 'pomodoro.modes.idle'),
    pomoFocusing: tr('todo', 'pomodoro.modes.focusing'),
    pomoStart: tr('todo', 'pomodoro.controls.start'),
    pomoPause: tr('todo', 'pomodoro.controls.pause'),
    minutes: tr('todo', 'pomodoro.settings.minutesUnit'),
    pomoToday: tr('todo', 'pomodoro.stats.todayLabel'),
    pomoStats: tr('workbench', 'pomodoro.today.statsButton'),
    pomoUnit: tr('todo', 'pomodoro.stats.pomodoroUnit'),
  },
  /** 题目集：ResourceAppWorkspace 左栏 + ExamContentView 工具条 + 启动台 / 识别导入 / 题库 / 做题 */
  exam: {
    title: tr('learningHub', 'resourceType.exam'),
    search: tr('workbench', 'resourceHome.search'),
    all: tr('common', 'all'),
    recent: tr('workbench', 'resourceHome.recent'),
    itemCount: (n: number) => tr('workbench', 'resourceHome.itemCount', { count: n }),
    selectTitle: tr('workbench', 'resourceWorkspace.selectTitle'),
    selectHint: tr('workbench', 'resourceWorkspace.selectHint'),
    newExam: tr('workbench', 'resourceHome.newExam'),
    tab: {
      bank: tr('learningHub', 'exam.tab.questionBank'),
      practice: tr('learningHub', 'exam.tab.practice'),
      more: tr('learningHub', 'exam.tab.more'),
      add: tr('learningHub', 'exam.tab.addQuestion'),
      export: tr('learningHub', 'exam.tab.export'),
      mastery: tr('learningHub', 'exam.shell.mastery'),
      correctRate: tr('learningHub', 'exam.shell.correctRate'),
    },
    launcher: {
      empty: tr('exam_sheet', 'questionBank.empty'),
      choose: tr('practice', 'questionBank.emptyChoosePath'),
      cards: [
        [tr('exam_sheet', 'questionBank.create.title'), tr('practice', 'questionBank.emptyCreateDesc')],
        [tr('exam_sheet', 'aiGeneration.title'), tr('exam_sheet', 'aiGeneration.launcherCardDesc')],
        [tr('exam_sheet', 'questionBank.import'), tr('practice', 'questionBank.emptyImportDesc')],
        [tr('exam_sheet', 'csv.import_title'), tr('practice', 'questionBank.emptyCsvDesc')],
      ] as Array<[string, string]>,
      dropHint: tr('practice', 'questionBank.emptyDropHint'),
      overlay: tr('drag_drop', 'overlay.drop_files_here_with_format', {
        formats: [tr('drag_drop', 'file_types.image'), tr('drag_drop', 'file_types.document')].join(', '),
      }),
      maxFiles: tr('drag_drop', 'overlay.max_files', { max: 20 }),
    },
    up: {
      title: tr('exam_sheet', 'uploader.header_title'),
      desc: tr('exam_sheet', 'uploader.header_desc'),
      steps: [tr('exam_sheet', 'uploader.steps.select'), tr('exam_sheet', 'uploader.steps.processing'), tr('exam_sheet', 'uploader.steps.summary')],
      drop: tr('exam_sheet', 'uploader.drop_or_click'),
      formats: tr('exam_sheet', 'uploader.supported_formats_all'),
      remove: tr('exam_sheet', 'uploader.remove'),
      parseModel: tr('exam_sheet', 'uploader.parse_model'),
      defaultModel: tr('settings', 'placeholders.use_default_model'),
      back: tr('common', 'actions.back'),
      parse: tr('exam_sheet', 'uploader.parse_document'),
      manual: tr('exam_sheet', 'uploader.manual_create_link'),
      phases: [
        tr('exam_sheet', 'uploader.phases.preparing'),
        tr('exam_sheet', 'uploader.phases.recognizing'),
        tr('exam_sheet', 'uploader.phases.parsing'),
        tr('exam_sheet', 'uploader.phases.done'),
      ],
      rendering: (c: number, n: number) => tr('exam_sheet', 'uploader.rendering_pages', { current: c, total: n }),
      parsingStarted: (n: number) => tr('exam_sheet', 'uploader.parsing_started', { chunks: n }),
      ocrPage: (c: number, n: number) => tr('exam_sheet', 'uploader.ocr_image_progress', { current: c, total: n }),
      ocrDone: (n: number) => tr('exam_sheet', 'uploader.ocr_phase_done', { total: n }),
      structuring: (c: number, n: number) => tr('exam_sheet', 'uploader.structuring_questions', { current: c, total: n }),
      parsedCount: (n: number) => tr('exam_sheet', 'uploader.parsed_count', { count: n }),
      cancel: tr('exam_sheet', 'uploader.cancel_import'),
      pageStatus: tr('exam_sheet', 'uploader.page_status_label'),
      parsedLabel: tr('exam_sheet', 'uploader.parsed_questions_label'),
      waiting: tr('exam_sheet', 'uploader.waiting_ai'),
      options: (n: number) => tr('exam_sheet', 'uploader.options_count', { count: n }),
      answer: (a: string) => tr('exam_sheet', 'uploader.answer_prefix', { answer: a }),
      complete: tr('exam_sheet', 'uploader.import_complete_title'),
      total: tr('exam_sheet', 'uploader.total_questions'),
      pages: tr('exam_sheet', 'uploader.page_count'),
      typeDist: tr('exam_sheet', 'uploader.question_type_dist'),
      filter: tr('exam_sheet', 'uploader.filter_questions'),
      filterHint: tr('exam_sheet', 'uploader.filter_hint'),
      again: tr('exam_sheet', 'uploader.continue_import'),
      view: tr('exam_sheet', 'uploader.view_questions'),
    },
    type: {
      single_choice: tr('exam_sheet', 'questionTypes.single_choice'),
      fill_blank: tr('exam_sheet', 'questionTypes.fill_blank'),
      short_answer: tr('exam_sheet', 'questionTypes.short_answer'),
      calculation: tr('exam_sheet', 'questionTypes.calculation'),
    },
    bank: {
      mastery: tr('practice', 'questionBank.masteredLabel'),
      start: tr('practice', 'questionBank.startPractice'),
      search: tr('practice', 'questionBank.searchPlaceholder'),
      manage: tr('exam_sheet', 'questionBank.manage'),
      all: tr('practice', 'questionBank.all'),
      newQ: tr('practice', 'questionBank.status.new'),
      statusNew: tr('practice', 'questionBank.statusShort.new'),
      diff: {
        easy: tr('practice', 'questionBank.difficultyShort.easy'),
        medium: tr('practice', 'questionBank.difficultyShort.medium'),
        hard: tr('practice', 'questionBank.difficultyShort.hard'),
        very_hard: tr('practice', 'questionBank.difficultyShort.veryHard'),
      },
    },
    q: {
      sequential: tr('practice', 'editor.modeShort.sequential'),
      total: tr('practice', 'editor.totalQuestions'),
      mastered: tr('practice', 'questionBank.stats.mastered'),
      review: tr('practice', 'editor.needsReview'),
      rate: tr('exam_sheet', 'questionBank.stats.correctRate'),
      singleChoice: tr('practice', 'editor.questionType.singleChoice'),
      medium: tr('exam_sheet', 'questionBank.difficulty.medium'),
      statusNew: tr('practice', 'questionBank.status.new'),
      statusReview: tr('practice', 'questionBank.status.review'),
      sourceImages: tr('common', 'question_bank.source_images'),
      submit: tr('practice', 'editor.submitAnswer'),
      hint: tr('practice', 'editor.inlineShortcutHint'),
      hintAfter: tr('practice', 'editor.inlineShortcutHintAfterSubmit'),
      notes: tr('practice', 'editor.myNotes'),
      addNote: tr('practice', 'editor.clickToAdd'),
      prev: tr('practice', 'editor.prevQuestion'),
      next: tr('practice', 'editor.nextQuestion'),
      correct: tr('practice', 'editor.correct'),
      wrong: tr('practice', 'editor.wrong'),
      answerWrong: tr('practice', 'editor.answerWrong'),
      correctAnswer: tr('practice', 'editor.correctAnswerLabel'),
      retry: tr('practice', 'editor.retry'),
      viewExplanation: tr('practice', 'editor.viewExplanation'),
      ask: tr('exam_sheet', 'followUp.askAction'),
      similar: tr('exam_sheet', 'followUp.similarAction'),
      ai: tr('practice', 'editor.aiAnalysis'),
      aiRunning: tr('practice', 'editor.aiAnalyzing'),
      cancel: tr('common', 'cancel'),
    },
  },
  res: {
    search: tr('workbench', 'resourceHome.search'),
    all: tr('common', 'all'),
    recent: tr('workbench', 'resourceHome.recent'),
    itemCount: (n: number) => tr('workbench', 'resourceHome.itemCount', { count: n }),
    empty: tr('workbench', 'resourceHome.empty'),
    needSelection: tr('workbench', 'resourceHome.settingsNeedSelection'),
    selectTitle: tr('workbench', 'resourceWorkspace.selectTitle'),
    selectHint: tr('workbench', 'resourceWorkspace.selectHint'),
  },
  essay: {
    title: tr('workbench', 'apps.essay'),
    settings: tr('workbench', 'resourceHome.essaySettings'),
    newEssay: tr('workbench', 'resourceHome.newEssay'),
    importImages: tr('essay_grading', 'import_images.button'),
    round: (n: number) => tr('essay_grading', 'round.label', { number: n }),
    topic: tr('essay_grading', 'topic.toggle_label'),
    emptyDesc: tr('essay_grading', 'empty_state.description'),
    pasteHint: tr('essay_grading', 'empty_state.paste_hint'),
    dropHint: tr('essay_grading', 'empty_state.drop_hint'),
    ocr: tr('essay_grading', 'empty_state.ocr_hint'),
    sample: tr('essay_grading', 'workbench.sample.fill_button'),
    stat: {
      han: tr('essay_grading', 'stats.han_chars'),
      en: tr('essay_grading', 'stats.english_words'),
      para: tr('essay_grading', 'workbench.stats.paragraphs'),
      punct: tr('essay_grading', 'stats.punctuation_total'),
      chars: tr('essay_grading', 'stats.characters'),
    },
    grade: tr('essay_grading', 'actions.grade'),
    cancel: tr('common', 'cancel'),
    result: tr('essay_grading', 'result_section.title'),
    waitTitle: tr('essay_grading', 'result_empty.title'),
    waitDesc: tr('essay_grading', 'result_empty.description'),
    waiting: tr('essay_grading', 'progress.waiting_response'),
    lock: tr('essay_grading', 'grading_lock.hint'),
    phase: {
      preparing: tr('essay_grading', 'progress.phase_preparing'),
      annotating: tr('essay_grading', 'progress.phase_annotating'),
      polishing: tr('essay_grading', 'progress.phase_polishing'),
    },
    generated: (n: number) => tr('essay_grading', 'progress.chars_generated', { count: n }),
    tab: {
      overview: tr('essay_grading', 'sections.tab_overview'),
      details: tr('essay_grading', 'sections.tab_details'),
      polish: tr('essay_grading', 'sections.tab_polish'),
    },
    filter: {
      all: tr('essay_grading', 'legend.filter_all'),
      errors: tr('essay_grading', 'legend.filter_errors'),
      suggestions: tr('essay_grading', 'legend.filter_suggestions'),
      highlights: tr('essay_grading', 'legend.filter_highlights'),
    },
    expand: tr('essay_grading', 'legend.expand'),
    mistakes: tr('essay_grading', 'mistakes.label'),
    cards: tr('essay_grading', 'make_cards.label'),
    afterGrading: tr('essay_grading', 'make_cards.disabled_grading'),
    total: tr('essay_grading', 'score.total'),
    pass: tr('essay_grading', 'score.grade.pass'),
    dims: tr('essay_grading', 'score.dimensions'),
    polishDesc: tr('essay_grading', 'sections.polish_desc'),
    hideDiff: tr('essay_grading', 'result_ui.polish_hide_diff'),
    original: tr('essay_grading', 'sections.original'),
    polished: tr('essay_grading', 'sections.polished'),
    copy: tr('common', 'copy'),
  },
  trans: {
    title: tr('workbench', 'apps.translation'),
    settings: tr('workbench', 'resourceHome.translationSettings'),
    newTranslation: tr('workbench', 'resourceHome.newTranslation'),
    hint: tr('translation', 'contentView.empty_hint'),
    en: tr('translation', 'languages.en'),
    zh: tr('translation', 'languages.zh-CN'),
    auto: tr('translation', 'workbench.toolbar.auto_translate'),
    sync: tr('translation', 'sync_scroll'),
    source: tr('translation', 'source_section.title'),
    target: tr('translation', 'target_section.title'),
    placeholder: tr('translation', 'source_section.placeholder'),
    resultPlaceholder: tr('translation', 'target_section.placeholder'),
    samples: tr('translation', 'workbench_core.samples_label'),
    sampleEn: tr('translation', 'workbench_core.sample_en'),
    sampleZh: tr('translation', 'workbench_core.sample_zh'),
    dropHint: tr('translation', 'workbench_core.drop_hint_inline'),
    translate: tr('translation', 'actions.translate'),
    translating: tr('translation', 'actions.translating'),
    cancel: tr('common', 'cancel'),
    sc: {
      translate: tr('translation', 'workbench_ui.shortcut_translate'),
      swap: tr('translation', 'workbench_ui.shortcut_swap'),
      cancel: tr('translation', 'workbench_ui.shortcut_cancel'),
    },
    saving: tr('translation', 'contentView.save_saving'),
    saved: tr('translation', 'contentView.save_saved'),
  },
};
